utils::globalVariables(c(
  "keep", "bin", "rawLR", "rawLR_short",
  ".N", "lr", "log2_short", "chromosome",
  "target", "start", "end", "mid",
  "length", "count", "count_short", "count_medium",
  "is_target", "is_backbone", "gc", "type",
  "label", "smooth_log2", "mean", "gpos",
  "gstart", "gstop", "allele_ratio", "allele_ratio_use",
  "allele_ratio_corrected2", "RD", "AD", "DP",
  "maf", "refmedian", "refmedian_short", "xmedian",
  "xmedian_short", "ymedian", "male", "nonPA",
  "corrected_lr", "i.corrected_lr", "V1", "is_tiled",
  "start_pos", "end_pos", "sample", "gene",
  "backbone_weight", "sort_chr", "sort_fac", "smoothed_log2",
  "window_seq", "window_id", "sd_smoothed", "N",
  ".", "aa", "AF", "AF_t",
  "AF.T", "ALT", "alt_allele", "alteration",
  "Amino_acids", "ANNOT", "AO", "AO.T",
  "arm", "arm_loh", "arm_median", "arm_noloh",
  "background_maf", "band", "bed_name", "bg",
  "bg_median", "bid", "bin_id", "bin_idx",
  "CANONICAL", "category", "centromeric", "chr_factor",
  "chrom", "chromosome_name", "Chromosome/scaffold name", "clean_chr",
  "CLIN_SIG", "Consequence", "count_all", "custom_HRD",
  "depth", "dif", "DP.T", "effect",
  "ensembl_gene_id", "ensembl_gene_id_version", "Exon region end (bp)", "Exon region start (bp)",
  "exonic", "farthest", "feature", "focal_gain",
  "focal_loss", "fraction", "g_idx", "Gene end (bp)",
  "Gene name", "Gene stable ID", "Gene start (bp)", "gene_biotype",
  "gene_end", "gene_start", "gene_symbol", "genes",
  "gnomAD_AF", "gnomADe_AF", "gnomADg_AF", "hotkey",
  "hotkey_end", "hotkey_start", "hotspots_inframes", "hotspots_snvs",
  "hotspots_splice_hg19", "hotspots_splice_hg38", "hugo_symbol", "id",
  "ID", "imbalance", "IMPACT", "is_hotspot",
  "is_indel", "is_rare_snp", "left", "local_cnv",
  "local_gain", "local_loss", "local_snp_bg", "logDP",
  "loh", "loh_raw", "loh_smooth", "long_cnv",
  "long_median", "m", "maf_diff", "male_from_x",
  "male_from_y", "min_d", "MSI", "n_bins",
  "nbrOfLoci", "nudge", "plot_count", "plot_value",
  "point mutation", "PolyPhen", "pos", "pos_1M",
  "ppos", "predicted_gis", "Protein_position", "REF",
  "ref_allele", "relevance", "right", "sd_count",
  "seg_mean", "selected_genes", "SIFT", "snp",
  "snps", "somatic_maf", "start_mb", "symbol",
  "SYMBOL", "target type", "telomeric", "tg",
  "tg_median", "tid", "transitions_val", "vaf_threshold",
  "value", "var_type"
))
